version: "3"

services:

  redis:
    container_name: redis-container
    image: "redis:latest"
    ports: 
      - "6379:6379"
    restart: always
    command: "redis-server"

  snowflake-optimizer:
    container_name: snowflake-optimizer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/snowflake-backend
    ports:
      - "8080:8080"
    expose:
        - "8080"
    restart: always
    command: "python manage.py runserver 0.0.0.0:80"
    links: 
      - redis
    # depends_on: 
    #   - celery
    
  celery:
    container_name: celery-container
    build: 
      context: .
      dockerfile: Dockerfile.celery
    command: "celery  -A snowflake_optimizer worker -l INFO"
    volumes:
      - .:/snowflake-optimizer
    restart: always
    links:
      - redis
    depends_on: 
      - snowflake-optimizer
  

      
