# Generated by Django 3.1.2 on 2020-11-14 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('snowflake_instances', '0001_initial')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_users', '0002_auto_20201028_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('instance_name', models.CharField(max_length=50)),
                ('instance_user', models.CharField(max_length=50)),
                ('instance_password', models.TextField()),
                ('instance_role', models.CharField(default='ACCOUNTADMIN', max_length=50)),
                ('instance_account', models.CharField(max_length=200, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_users.companydetails')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instance_account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowflake_instances.instanceaccounttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
