# Generated by Django 3.1.2 on 2020-11-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowflake_instances', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instances',
            name='last_connected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
