# Generated by Django 3.1.4 on 2021-01-17 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneQueryRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('rule_name', models.CharField(max_length=255, unique=True)),
                ('rule_description', models.TextField(blank=True, null=True)),
                ('rule_evaluation_query', models.TextField()),
                ('rule_evaluation_equation', models.TextField()),
                ('failed_if', models.BooleanField()),
                ('rule_recommendation', models.TextField()),
                ('rule_dataset_query', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneQueryRuleArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('article_link', models.TextField()),
                ('one_query_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule_engine.onequeryrules')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
