# Generated by Django 3.1.4 on 2021-01-21 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snowflake_instances', '0002_instances_last_connected'),
        ('rule_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowflake_instances.instances')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='onequeryrulearticles',
            name='one_query_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_query_rule_related_articles', to='rule_engine.onequeryrules'),
        ),
        migrations.CreateModel(
            name='IgnoreRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowflake_instances.instances')),
                ('one_query_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule_engine.onequeryrules')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditsResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('dataset', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule_engine.audits')),
                ('one_query_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule_engine.onequeryrules')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
