# Generated by Django 3.1.4 on 2021-01-27 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snowflake_instances', '0002_instances_last_connected'),
        ('rule_engine', '0002_auto_20210121_1143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ignorerules',
            unique_together={('one_query_rule', 'instance')},
        ),
        migrations.CreateModel(
            name='AuditNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule_engine.audits')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
