# Generated by Django 3.1.5 on 2021-01-27 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rule_engine', '0003_auto_20210127_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='AuditNotifications',
            new_name='DoNotNotifyUsers',
        ),
    ]
