# Generated by Django 3.1.5 on 2021-01-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0004_auto_20210127_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditstatus',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='auditstatus',
            name='modified_date',
        ),
    ]
