# Generated by Django 3.1.5 on 2021-01-27 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rule_engine', '0005_auto_20210127_1215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donotnotifyusers',
            unique_together={('audit', 'user')},
        ),
    ]
