# Generated by Django 3.1.5 on 2021-02-05 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0006_auto_20210127_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('rule_name', models.CharField(max_length=255, unique=True)),
                ('rule_description', models.TextField(blank=True, null=True)),
                ('rule_evaluation_query', models.TextField()),
                ('rule_evaluation_equation', models.TextField()),
                ('failed_if', models.BooleanField()),
                ('rule_recommendation', models.TextField()),
                ('rule_dataset_query', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule_engine.audits')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
