# Generated by Django 3.1.6 on 2021-02-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0007_appliedrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='audits',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
