# Generated by Django 3.1.6 on 2021-02-05 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0008_audits_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audits',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule_engine.auditstatus'),
        ),
    ]
