# Generated by Django 3.1.6 on 2021-02-05 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0009_auto_20210205_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditsresults',
            name='one_query_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule_engine.appliedrule'),
        ),
    ]
