# Generated by Django 3.1.6 on 2021-02-06 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rule_engine', '0013_auto_20210206_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicablerule',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='audits',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system_users.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApplicableRuleArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('article_link', models.TextField()),
                ('applicable_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicable_rule_related_articles', to='rule_engine.applicablerule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
