# Generated by Django 3.1.6 on 2021-02-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0014_auto_20210206_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditsresults',
            old_name='one_query_rule',
            new_name='applicable_rule',
        ),
    ]
