
#clustering history
SQL_AUTOMATIC_CLUSTERING_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.AUTOMATIC_CLUSTERING_HISTORY;'
TABLE_AUTOMATIC_CLUSTERING_HISTORY = ''

#account ussage columns
SQL_ACCOUNT_USAGE_COLUMNS = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.COLUMNS;'
TABLE_COLUMNS = ''

# --HANGS
#copy account usage history
SQL_ACCOUNT_USAGE_COPY_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY;'
TABLE_COPY_HISTORY = ''

#account usage history
SQL_ACCOUNT_USAGE_DATABASES = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASES;'
TABLE_DATABASES = ''

#--NOT BEING POPULATED
#databases storage usage history
SQL_DATABASE_STORAGE_USAGE_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY; '
TABLE_DATABASE_STORAGE_USAGE_HISTORY = ''

#data transfer history
SQL_DATA_TRANSFER_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.DATA_TRANSFER_HISTORY;'
TABLE_DATA_TRANSFER_HISTORY = ''

#file formats
SQL_FILE_FORMATS = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.FILE_FORMATS;'
TABLE_FILE_FORMATS = ''

#functions
SQL_FUNCTIONS = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.FUNCTIONS;'
TABLE_FUNCTIONS = ''

#grants to roles
SQL_GRANTS_TO_ROLES = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES;'
TABLE_GRANTS_TO_ROLES = ''

#grants to users
SQL_GRANTS_TO_USERS = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS;'
TABLE_GRANTS_TO_USERS = ''

#load history
SQL_LOAD_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.LOAD_HISTORY;'
TABLE_LOAD_HISTORY = ''

#login history
SQL_LOGIN_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY;'
TABLE_LOGIN_HISTORY = 'login_history'

#materialized view refresh history
SQL_MATERIALIZED_VIEW_REFRESH_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.MATERIALIZED_VIEW_REFRESH_HISTORY;'
TABLE_MATERIALIZED_VIEW_REFRESH_HISTORY  = ''

# -- Credits used by date.
#metering daily history
SQL_METERING_DAILY_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY;'
TABLE_METERING_DAILY_HISTORY  = ''

#-- Compute used including Cloud Services
#metering history
SQL_METERING_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY; '
TABLE_METERING_HISTORY  = ''

#pipes
SQL_PIPES = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.PIPES;'
TABLE_PIPES= ''

#pipe usage history
SQL_PIPE_USAGE_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY;'
TABLE_PIPE_USAGE_HISTORY = ''

#-- Important
#query history
# SQL_QUERY_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY;'
# TABLE_QUERY_HISTORY = ''

#referential constraints
SQL_REFERENTIAL_CONSTRAINTS = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.REFERENTIAL_CONSTRAINTS;'
TABLE_REFERENTIAL_CONSTRAINTS = ''

#replication usage history
SQL_REPLICATION_USAGE_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.REPLICATION_USAGE_HISTORY;'
TABLE_REPLICATION_USAGE_HISTORY = ''

#roles
SQL_ROLES = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.ROLES;'
TABLE_ROLES = ''

#schemata
SQL_SCHEMATA = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.SCHEMATA;'
TABLE_SCHEMATA = ''

#search optimization history
#--opt
SQL_SEARCH_OPTIMIZATION_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.SEARCH_OPTIMIZATION_HISTORY;'
TABLE_SEARCH_OPTIMIZATION_HISTORY = ''

# --opt
#sequences
SQL_SEQUENCES = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.SEQUENCES;'
TABLE_SEQUENCES = ''

#--opt
#stages
SQL_STAGES = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.STAGES;'
TABLE_STAGES = ''

# --opt
#stage storage usage history
SQL_STAGE_STORAGE_USAGE_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.STAGE_STORAGE_USAGE_HISTORY;'
TABLE_STAGE_STORAGE_USAGE_HISTORY = ''

#--opt
#storage usage
SQL_STORAGE_USAGE = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE;'
TABLE_STORAGE_USAGE = ''

#tables
SQL_TABLES = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES;'
TABLE_TABLES = ''

#constraints
SQL_TABLE_CONSTRAINTS = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_CONSTRAINTS;'
TABLE_TABLE_CONSTRAINTS = ''

#table storage metrics
# --opt
SQL_TABLE_STORAGE_METRICS = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;'
TABLE_TABLE_STORAGE_METRICS = ''

#users
# --opt
# SQL_USERS = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.USERS;'
# TABLE_USERS = ''

#views
# --opt
SQL_VIEWS = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.VIEWS;'
TABLE_VIEWS = ''

#warehouse load history
#--opt
SQL_WAREHOUSE_LOAD_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY;' 
TABLE_WAREHOUSE_LOAD_HISTORY = ''

#warehouse metering history
# --opt
SQL_WAREHOUSE_METERING_HISTORY = 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY;'
TABLE_WAREHOUSE_METERING_HISTORY = ''

#preview data transfer daily history
SQL_PREVIEW_DATA_TRANSFER_DAILY_HISTORY = 'SELECT * FROM SNOWFLAKE.ORGANIZATION_USAGE.PREVIEW_DATA_TRANSFER_DAILY_HISTORY;'
TABLE_PREVIEW_DATA_TRANSFER_DAILY_HISTORY = ''

#preview metering transfer daily history
SQL_PREVIEW_METERING_DAILY_HISTORY = 'SELECT * FROM SNOWFLAKE.ORGANIZATION_USAGE.PREVIEW_METERING_DAILY_HISTORY;'
TABLE_PREVIEW_METERING_DAILY_HISTORY = ''

#preview storage daily history
SQL_PREVIEW_STORAGE_DAILY_HISTORY = 'SELECT * FROM SNOWFLAKE.ORGANIZATION_USAGE.PREVIEW_STORAGE_DAILY_HISTORY;'
TABLE_PREVIEW_STORAGE_DAILY_HISTORY = ''

#login history
SQL_LOGIN_HISTORY = 'SELECT * FROM SNOWFLAKE.READER_ACCOUNT_USAGE.LOGIN_HISTORY;'
TABLE_LOGIN_HISTORY = ''

#query history
SQL_QUERY_HISTORY = 'SELECT * FROM SNOWFLAKE.READER_ACCOUNT_USAGE.QUERY_HISTORY;'
TABLE_QUERY_HISTORY = ''

#resource monitors
# SQL_RESOURCE_MONITORS = 'SELECT * FROM SNOWFLAKE.READER_ACCOUNT_USAGE.RESOURCE_MONITORS;'
# TABLE_RESOURCE_MONITORS = ''

#storage usage
SQL_STORAGE_USAGE = 'SELECT * FROM SNOWFLAKE.READER_ACCOUNT_USAGE.STORAGE_USAGE;'
TABLE_STORAGE_USAGE = ''

#warehouse metering history
SQL_WAREHOUSE_METERING_HISTORY = 'SELECT * FROM SNOWFLAKE.READER_ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY;'
TABLE_WAREHOUSE_METERING_HISTORY = ''