# Generated by Django 3.1.2 on 2020-10-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
