#account level
SQL_ACCOUNT_PARAMETERS = 'SHOW PARAMETERS IN ACCOUNT;'
TABLE_ACCOUNT_PARAMETERS = 'account_parameters'
INDEX_ACCOUNT_PARAMETERS = 'ID'

#database
SQL_DATABASES = 'SHOW DATABASES;'
TABLE_DATABASES = 'instance_databases'
INDEX_DATABASES = 'ID'

#db level
SQL_DB_LEVEL_PARAMETERS = "SHOW PARAMETERS IN DATABASE {};"
TABLE_DB_LEVEL_PARAMETERS = 'parameters_in_database'
INDEX_DB_LEVEL_PARAMETERS = 'ID'

#schema
SQL_SCHEMAS = 'SHOW SCHEMAS;'
TABLE_SCHEMAS = 'instance_databases_schemas'
INDEX_SCHEMAS = 'ID'

#schema level
SQL_SCHEMA_PARAMETERS = "SHOW PARAMETERS IN SCHEMA {}.{};"
TABLE_SCHEMA_PARAMETERS = 'parameters_in_schemas'
INDEX_SCHEMA_PARAMETERS = 'ID'

##SQL_SCHEMAS_IN_DATABASES = 'SHOW SCHEMAS IN {}'