#account level
SQL_ACCOUNT_PARAMETERS = 'SHOW PARAMETERS IN ACCOUNT;'
TABLE_ACCOUNT_PARAMETERS = 'account_parameters'

#database
SQL_DATABASES = 'SHOW DATABASES;'
TABLE_DATABASES = 'instance_databases'

#db level
SQL_DB_LEVEL_PARAMETERS = "SHOW PARAMETERS IN DATABASE {};"
TABLE_DB_LEVEL_PARAMETERS = 'parameters_in_database'

#schema
SQL_SCHEMAS = 'SHOW SCHEMAS;'
TABLE_SCHEMAS = 'instance_databases_schemas'

#schema level
SQL_SCHEMA_PARAMETERS = "SHOW PARAMETERS IN SCHEMA {}.{};"
TABLE_SCHEMA_PARAMETERS = 'parameters_in_schemas'

SQL_SCHEMAS_IN_DATABASES = 'SHOW SCHEMAS IN {}'