# Generated by Django 3.1.2 on 2020-10-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowflake_connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instances',
            name='instance_password',
            field=models.TextField(),
        ),
    ]
