import sys
sys.path.insert(constants.1, constants. '/snowflake-backend/snowflake/collect_metadata')
import constants


queries_tables_list = [
    (constants.SQL_INFORMATION_SCHEMA_APPLICABLE_ROLES, constants.TABLE_INFORMATION_SCHEMA_APPLICABLE_ROLES),
    (constants.SQL_INFORMATION_SCHEMA_COLUMNS, constants.TABLE_INFORMATION_SCHEMA_COLUMNS),
    (constants.SQL_INFORMATION_SCHEMA_DATABASES, constants.TABLE_INFORMATION_SCHEMA_DATABASES),
    (constants.SQL_INFORMATION_SCHEMA_ENABLED_ROLES, constants.TABLE_INFORMATION_SCHEMA_ENABLED_ROLES),
    (constants.SQL_INFORMATION_SCHEMA_EXTERNAL_TABLES, constants.TABLE_INFORMATION_SCHEMA_EXTERNAL_TABLES),
    (constants.SQL_INFORMATION_SCHEMA_FILE_FORMATS, constants.TABLE_INFORMATION_SCHEMA_FILE_FORMATS),
    (constants.SQL_INFORMATION_SCHEMA_FUNCTIONS, constants.TABLE_INFORMATION_SCHEMA_FUNCTIONS),
    (constants.SQL_INFORMATION_SCHEMA_CATALOG_NAME, constants.TABLE_INFORMATION_SCHEMA_CATALOG_NAME),
    (constants.SQL_INFORMATION_SCHEMA_LOAD_HISTORY, constants.TABLE_INFORMATION_SCHEMA_LOAD_HISTORY),
    (constants.SQL_INFORMATION_SCHEMA_OBJECT_PRIVILEGES, constants.TABLE_INFORMATION_SCHEMA_OBJECT_PRIVILEGES),
    (constants.SQL_INFORMATION_SCHEMA_PIPES, constants.TABLE_INFORMATION_SCHEMA_PIPES),
    (constants.SQL_INFORMATION_SCHEMA_PROCEDURES, constants.TABLE_INFORMATION_SCHEMA_PROCEDURES),
    (constants.SQL_INFORMATION_SCHEMA_REFERENTIAL_CONSTRAINTS, constants.TABLE_INFORMATION_SCHEMA_REFERENTIAL_CONSTRAINTS),
    (constants.SQL_INFORMATION_SCHEMA_REPLICATION_DATABASES, constants.TABLE_INFORMATION_SCHEMA_REPLICATION_DATABASES),
    (constants.SQL_INFORMATION_SCHEMA_SCHEMATA, constants.TABLE_INFORMATION_SCHEMA_SCHEMATA),
    (constants.SQL_INFORMATION_SCHEMA_SEQUENCES, constants.TABLE_INFORMATION_SCHEMA_SEQUENCES),
    (constants.SQL_INFORMATION_SCHEMA_STAGES, constants.TABLE_INFORMATION_SCHEMA_STAGES),
    (constants.SQL_INFORMATION_SCHEMA_TABLES, constants.TABLE_INFORMATION_SCHEMA_TABLES),
    (constants.SQL_INFORMATION_SCHEMA_TABLE_CONSTRAINTS, constants.TABLE_INFORMATION_SCHEMA_TABLE_CONSTRAINTS),
    (constants.SQL_INFORMATION_SCHEMA_TABLE_PRIVILEGES, constants.TABLE_INFORMATION_SCHEMA_TABLE_PRIVILEGES),
    (constants.SQL_INFORMATION_SCHEMA_TABLE_STORAGE_METRICS, constants.TABLE_INFORMATION_SCHEMA_TABLE_STORAGE_METRICS),
    (constants.SQL_INFORMATION_SCHEMA_USAGE_PRIVILEGES, constants.TABLE_INFORMATION_SCHEMA_USAGE_PRIVILEGES),
    (constants.SQL_INFORMATION_SCHEMA_VIEWS, constants.TABLE_INFORMATION_SCHEMA_VIEWS)
]