# Generated by Django 3.1.2 on 2020-10-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
