# Generated by Django 3.1.2 on 2020-10-16 08:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedmembers',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_users.user'),
            preserve_default=False,
        ),
    ]
